config/routes.rb
TwitterApp::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'post/create' => 'posts#create', :as => :create_post, :via => :post

  get '/:username/follower' => 'users#follower', :as => :follower
  get '/:username' => 'users#index', :constrain => { :username => /[a-zA-Z-]+/ }
  get '/:username' => 'users#index', :as => :user_detail
  resources :users
  resources :posts
  resources :followers
  resources :sessions
  root :to => 'posts#index'

end

app/models/follower.rb
class Follower < ActiveRecord::Base

  belongs_to :follower, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  has_many :followers
  has_many :friends, :through => :friendships
  has_many :posts

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery



end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  before_filter :login_required, :only => [:create, :destroy]

  def create
    @follower = current_user.followers.build(:follower_id => params[:follower_id])
    if @follower.save
      follower = User.find params[:follower_id]
      flash[:notice] = "Now you are following "+follower.username.to_s
      redirect_to root_url
    else
      flash[:error] = "Error occurred when adding friend."
      redirect_to root_url
    end
  end

  def destroy
    @follower = current_user.friendships.find(params[:id])
    @follower.destroy
    flash[:notice] = "Successfully destroyed follower."
    redirect_to root_url
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :login_required, :only => [:index]

  def index
    @posts = Post.all(:order => "created_at DESC")
  end

  def create
    @post = current_user.posts.create(
        :message => params[:message],
        :is_visible => params[:is_visible]
    )
    if @post
      redirect_to root_path
    else
      flash[:notice] = "Message failed to save."
      redirect_to posts_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

  def follower
    @followers = Follower.find_all_by_follower_id current_user.id
  end




end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_follower(follower_id)
    follower = Follower.find_by_user_id_and_follower_id follower_id, current_user.id
    if follower
      user = User.find follower_id
       p "----------------------------"
      p user.username
      return user.username.to_s
    else
      return false
    end
  end

  def is_following(follower_id)
    user = current_user
    following = Follower.find_by_user_id_and_follower_id user.id,follower_id
    if following
      return true
    else
      return false
    end
  end

end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div style="float:right;"><%= render :partial => "users/login" %></div><br/><br/>
      <%= render :partial => 'shared/header' %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>

      <%= yield %>
      <%#= render :partial => "shared/footer" %>
    </div>
  </body>
</html>

app/views/posts/_message_form.html.erb
<div id="flash_error" style="display:none"></div>

<% if logged_in? %>
    <%= form_tag create_post_path do %>
        <%= label_tag(:message, "What are you doing?") %><br />
        <%= text_area_tag(:message, nil, :class => "input_box", :id=>'tweetBox', :onkeyup=>"countChar(this, 160)") %><br />
        <%= radio_button_tag('is_visible', true, ""  )%>
        <%= label_tag "Public Tweet"%>
        <%= radio_button_tag('is_visible',false  )%>
        <%= label_tag "Private Tweet"%>
        <br/><br/>
        <%= submit_tag("Tweet", :class => "btn" ) %>
    <% end %>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>
    <p><b>Posted <%= time_ago_in_words(post.created_at) %> ago</b></p>
    <span class="username"><%= link_to post.user.username, user_path(post.user.username,post.user.id)%>:</span>
    <%= post.message %>
    <% unless post.user_id == current_user.id %>
        <% case post.is_visible %>
<% when true %>
            <span><%= button_to "ReTweet", create_post_path(:message => post.message, :is_visible => true),:class=>"btn", :method => :post  %></span>
            <span class="color_golden"><i>This is Public Tweet.</i></span>
        <% when false %>
            <% if is_following(post.user_id) %>
                <br/><br/>
                <span>  <%= button_to "ReTweet", create_post_path(:message => post.message, :is_visible => true),:class=>"btn", :method => :post  %></span>
                <span class="color_golden"><i>This is Private Tweet.</i></span>
            <% else %>
                <br/><br/>
                <span class="color_golden">This is Private Tweet, so you cannot retweet it.</span>
            <% end %>
        <% end %>
    <% else %>
        <span> <%= button_to "ReTweet", create_post_path(:message => post.message, :is_visible => true),:class=>"btn", :method => :post  %></span>
        <% if post.is_visible %>
            <span class="color_golden"><i>This is Public Tweet.</i></span>
        <% else %>
            <span class="color_golden"><i>This is Private Tweet.</i></span>
        <% end %>
    <% end %>

<% end %>

app/views/posts/index.html.erb
<%= render :partial => "message_form" %>
<div id="posts">
  <%= render :partial => @posts %>
</div>
<%= link_to "Follow People", user_detail_path(current_user.username) %>  |
<%= link_to "My Followers", follower_path(current_user.username) %>

app/views/shared/_footer.html.erb
<div>
  © TweetApp  2013
</div>

app/views/shared/_header.html.erb
<div class="heading"> TweetApp </div>
<% unless current_user.nil? %>
    <%= render :partial => 'shared/menu' %>
<% end %>

app/views/shared/_menu.html.erb
<div class="menu">
  <%= link_to "home", root_path%>
  <%= link_to "Follow People", user_detail_path(current_user.username) %>
  <%= link_to "My Followers", follower_path(current_user.username) %>
</div>

app/views/shared/_no_user.html.erb
<div class="not_found">
  <% if follower == false %>
      There is no follower found.
  <% elsif follower == true %>
      There is no user to follow.
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.error_messages %>
    <div class="form">
      <p>
        <%= f.label :username %><br />
        <%= f.text_field :username %>
      </p>
      <p>
        <%= f.label :email, "Email Address" %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation, "Confirm Password" %><br />
        <%= f.password_field :password_confirmation %>
      </p>
    </div>
    <p><%= f.submit (@user.new_record? ? "Sign up" : "Update"), :class => 'btn' %></p>

<% end %>

app/views/users/_login.html.erb
<% if logged_in? %>
    Welcome <%= current_user.username %>! Not you?
    <%= link_to "Log out", logout_path %>
<% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>.
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/follower.html.erb
<% unless @followers.blank?  %>

    <% @followers.each do |follower| %>
        <div style="text-align: center;">
          <% if is_follower(follower.user_id) %>
              <%= is_follower(follower.user_id) %>
          <% else %>
              <%= render :partial => "shared/no_user", :locals => {:follower => false} %>
          <% end %>
        </div>

    <% end %>
<% else %>
    <%= render :partial => "shared/no_user", :locals => {:follower => false} %>
<% end %>

app/views/users/index.html.erb
<% unless @users.nil? %>
    <% @users.each do |user| %>
        <% if user.username != current_user.username %>
            <% if is_following(user.id) %>
                <div style="text-align: center;">
                  <span class="color">Following</span>  <span><%= user.username %></span>
                </div>
            <% else %>
                <div style="text-align: center;">
                  <span><%= user.username %></span> <span><%= link_to "Follow", followers_path(:follower_id => user), :method => :post %> </span>
                </div><br/>
            <% end %>

        <% end %>
    <% end %>
<% else %>
    <%= render :partial => "shared/no_user", :locals => {:following => false} %>
<% end %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= current_user.username %> Details</h1><br/>
<div> <span><b>Username:</b></span> <span><%= current_user.username %></span></div><br/><br/>
<div> <span><b>Email:</b></span> <span><%= current_user.email %></span></div><br/>